# SPDX-FileCopyrightText: 2023 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This workflow will test a Java project with Maven
# See https://github.com/jonashackt/github-actions-release-maven

name: Java Tests
on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn -U -B verify # -U: force updates for dependencies, -B: no user input
