# SPDX-FileCopyrightText: 2023 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This workflow will publish a Java project with Gradle
# For gradle wrapper validation see: https://github.com/marketplace/actions/gradle-wrapper-validation
# For gradle build see: https://github.com/marketplace/actions/gradle-build-action

name: Publish Snapshot to Maven Central

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.1.0
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.7.0
    - name: Publish to Maven Central
      run: ./gradlew publish
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        DD_CLIENT_VERSION: ${{ github.event.release.tag_name }}
